import type { Config } from "tailwindcss";
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontFamily: {
      default: "var(--custom-font)",
    },
    fontSize: {
      xxs: [
        "calc(var(--text-base-unit) * 4)",
        "calc(var(--text-line-base-unit) * 6)",
      ],
      xs: [
        "calc(var(--text-base-unit) * 5)",
        "calc(var(--text-line-base-unit) * 8)",
      ],
      sm: [
        "calc(var(--text-base-unit) * 7)",
        "calc(var(--text-line-base-unit) * 10)",
      ],
      base: [
        "calc(var(--text-base-unit) * 8)",
        "calc(var(--text-line-base-unit) * 12)",
      ],
      lg: [
        "calc(var(--text-base-unit) * 9)",
        "calc(var(--text-line-base-unit) * 14)",
      ],
      xl: [
        "calc(var(--text-base-unit) * 10)",
        "calc(var(--text-line-base-unit) * 14)",
      ],
      "2xl": [
        "calc(var(--text-base-unit) * 12)",
        "calc(var(--text-line-base-unit) * 16)",
      ],
      "3xl": [
        "calc(var(--text-base-unit) * 15)",
        "calc(var(--text-line-base-unit) * 18)",
      ],
      "4xl": [
        "calc(var(--text-base-unit) * 18)",
        "calc(var(--text-line-base-unit) * 20)",
      ],
      "5xl": ["calc(var(--text-base-unit) * 24)", "1"],
    },
    spacing: {
      "0": "0px",
      px: "1px",
      "0.5": "var(--spacing-base-unit)",
      "1": "calc(var(--spacing-base-unit) * 2)",
      "1.5": "calc(var(--spacing-base-unit) * 3)",
      "2": "calc(var(--spacing-base-unit) * 4)",
      "2.5": "calc(var(--spacing-base-unit) * 5)",
      "3": "calc(var(--spacing-base-unit) * 6)",
      "3.5": "calc(var(--spacing-base-unit) * 7)",
      "4": "calc(var(--spacing-base-unit) * 8)",
      "5": "calc(var(--spacing-base-unit) * 9)",
      "6": "calc(var(--spacing-base-unit) * 12)",
      "7": "calc(var(--spacing-base-unit) * 14)",
      "8": "calc(var(--spacing-base-unit) * 16)",
      "9": "calc(var(--spacing-base-unit) * 18)",
      "10": "calc(var(--spacing-base-unit) * 20)",
      "11": "calc(var(--spacing-base-unit) * 22)",
      "12": "calc(var(--spacing-base-unit) * 24)",
      "14": "calc(var(--spacing-base-unit) * 28)",
      "16": "calc(var(--spacing-base-unit) * 32)",
      "20": "calc(var(--spacing-base-unit) * 40)",
      "24": "calc(var(--spacing-base-unit) * 48)",
      "28": "calc(var(--spacing-base-unit) * 56)",
      "32": "calc(var(--spacing-base-unit) * 64)",
      "36": "calc(var(--spacing-base-unit) * 72)",
      "40": "calc(var(--spacing-base-unit) * 80)",
      "44": "calc(var(--spacing-base-unit) * 88)",
      "48": "calc(var(--spacing-base-unit) * 96)",
      "52": "calc(var(--spacing-base-unit) * 104)",
      "56": "calc(var(--spacing-base-unit) * 112)",
      "60": "calc(var(--spacing-base-unit) * 120)",
      "64": "calc(var(--spacing-base-unit) * 128)",
      "72": "calc(var(--spacing-base-unit) * 144)",
      "80": "calc(var(--spacing-base-unit) * 160)",
      "96": "calc(var(--spacing-base-unit) * 192)",
    },
    extend: {
      colors: {
        primary: "var(--primary-color)",
        darkerPrimary: "var(--darker-primary-color)",
        contrast: "var(--primary-contrast-color)",
        revas: {
          primary: {
            100: "#E5DBFF",
            200: "#CDBCF5",
            300: "#B99CFF",
            400: "#9F77FF",
            500: "#8154ec",
            600: "#6A3FCF",
            700: "#5434A1",
            800: "#351581",
          },
          blue: {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
          },
          green: {
            "50": "#ecfdf5",
            "100": "#d1fae5",
            "200": "#a7f3d0",
            "300": "#6ee7b7",
            "400": "#34d399",
            "500": "#10b981",
            "600": "#059669",
            "700": "#047857",
            "800": "#065f46",
            "900": "#064e3b",
          },
          yellow: {
            "50": "#fffbeb",
            "100": "#fef3c7",
            "200": "#fde68a",
            "300": "#fcd34d",
            "400": "#fbbf24",
            "500": "#f59e0b",
            "600": "#d97706",
            "700": "#b45309",
            "800": "#92400e",
            "900": "#78350f",
          },
          red: {
            "50": "#fef2f2",
            "100": "#fee2e2",
            "200": "#fecaca",
            "300": "#fca5a5",
            "400": "#f87171",
            "500": "#ef4444",
            "600": "#dc2626",
            "700": "#b91c1c",
            "800": "#991b1b",
            "900": "#7f1d1d",
          },
          gray: {
            50: "#F7F8FA",
            100: "#F7F8FA",
            200: "#F7F8FA",
            300: "#EFF1F4",
            400: "#DCDDE0",
            500: "#DCDDE0",
            600: "#8B8D91",
            700: "#8B8D91",
            800: "#6C6F75",
            900: "#3D4148",
            950: "#3D4148",
          },
          neutral: {
            "50": "#f9fafb",
            "100": "#f3f4f6",
            "200": "#e5e7eb",
            "300": "#d1d5db",
            "400": "#9ca3af",
            "500": "#6b7280",
            "600": "#4b5563",
            "700": "#374151",
            "800": "#1f2937",
            "900": "#111827",
          },
          black: "#000",
          white: "#fff",
        },
      },
      borderRadius: {
        default: "var(--border-radius)",
        inner: "var(--border-radius-inner)",
      },
      keyframes: {
        enterFromRight: {
          from: { opacity: "0", transform: 'translateX(200px)' },
          to: { opacity: "1", transform: 'translateX(0)' },
        },
        enterFromLeft: {
          from: { opacity: "0", transform: 'translateX(-200px)' },
          to: { opacity: "1", transform: 'translateX(0)' },
        },
        exitToRight: {
          from: { opacity: "1", transform: 'translateX(0)' },
          to: { opacity: "0", transform: 'translateX(200px)' },
        },
        exitToLeft: {
          from: { opacity: "1", transform: 'translateX(0)' },
          to: { opacity: "0", transform: 'translateX(-200px)' },
        },
        scaleIn: {
          from: { opacity: "0", transform: 'rotateX(-10deg) scale(0.9)' },
          to: { opacity: "1", transform: 'rotateX(0deg) scale(1)' },
        },
        scaleOut: {
          from: { opacity: "1", transform: 'rotateX(0deg) scale(1)' },
          to: { opacity: "0", transform: 'rotateX(-10deg) scale(0.95)' },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        fadeOut: {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
      },
      animation: {
        pageShow: "fadeIn 300ms cubic-bezier(0.16, 1, 0.3, 1)",
        scaleIn: 'scaleIn 200ms ease',
        scaleOut: 'scaleOut 200ms ease',
        fadeIn: 'fadeIn 200ms ease',
        fadeOut: 'fadeOut 200ms ease',
        enterFromLeft: 'enterFromLeft 250ms ease',
        enterFromRight: 'enterFromRight 250ms ease',
        exitToLeft: 'exitToLeft 250ms ease',
        exitToRight: 'exitToRight 250ms ease',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
} satisfies Config;
